#!/bin/bash

# List all tmux sessions and use fzf to select one
selected_session=$(tmux list-sessions -F '#S' | fzf)

# Check if a session was selected
if [ -n "$selected_session" ]; then
	if [[ -z $TMUX ]]; then
		# If not within tmux, attach
		tmux attach -t $selected_session
	else
		# If within tmux, switch
		tmux switch-client -t $selected_session
	fi
else
	echo "No session selected."
fi
